export const colors = {
    breakerBay: '#53a5a0',
    lightForestGreen: '#5db27b',
    summerGreen: '#95bea6',
    morningGlory: '#a0cdca',
    lightBlue: '#b2d9ef',
    shakespeare: '#56acdf',
    denim: '#2e70b4',
    midnightBlue: '#1d4873',
    purple: '#83568b',
    trueViolet: '#8777d6',
    melrose: '#bdb4e8',
    frenchLilac: '#e2bdea',
    paleChestnut: '#dda1ba',
    carissma: '#dc7f9b',
    brightLavender: '#cb86d9',
    lightGray: '#D3D3D3',
}

export const colorsArray = [
    colors.breakerBay,
    colors.lightForestGreen,
    colors.summerGreen,
    colors.morningGlory,
    colors.lightBlue,
    colors.shakespeare,
    colors.denim,
    colors.midnightBlue,
    colors.purple,
    colors.trueViolet,
    colors.melrose,
    colors.frenchLilac,
    colors.paleChestnut,
    colors.carissma,
    colors.brightLavender,
    colors.lightGray,
]